includes:
  - ../global.yaml

setup:
  model_name: ddpg
  action_mode: rl_none  # rl_none, rl_base, rl_none_coeff, rl_base_coeff

  total_steps: 200000  # Total environment steps
  eval_freq: 1024  # Frequency of model evaluation (in steps)

  learning_rate: 0.0028095326860480495  # for both actor and critic networks
  tau: 0.0010082105753620831
  batch_size: 256
  gradient_steps: 1
  learning_starts: 500
  buffer_size: 20000
  patience: 10  # Number of evaluations without improvement before early stopping
  lr_min: 0.00014571290176012956  # Minimum learning rate for learning rate scheduling
  lr_fraction: 0.95  # Fraction of total steps at which learning rate reaches minimum
  train_freq: 1
  q_value_print_freq: 500  # Frequency of Q-value printing during training (in steps)
  action_noise: None  # Exploration noise type (None = no noise, alternative: OrnsteinUhlenbeckActionNoise)
  gamma: 0.9852352143340127
  initial_action_bias: 0.3409250448637875 # Initial action bias as fraction of action space (0.0-1.0)
  net_arch:
    pi: [ 64, 64 ]     # Actor
    qf: [ 64, 64 ]    # Critic
