includes:
  - ../global.yaml

setup:
  model_name: ppo
  action_mode: rl_base  # rl_none, rl_base, rl_none_coeff, rl_base_coeff

  total_steps: 200000  # Total environment steps
  eval_freq: 2048 # Frequency of model evaluation (in steps)

  learning_rate: 0.004249335545960943
  n_steps: 1024
  batch_size: 256
  clip_range: 0.10445691984873462
  vf_coef: 0.4
  max_grad_norm: 0.5
  n_epochs: 5
  target_kl: null
  patience: 10  # Number of evaluations without improvement before early stopping
  lr_min: 1.5346058004082032e-05  # Minimum learning rate for learning rate scheduling
  lr_fraction: 0.9  # Fraction of total steps at which learning rate reaches minimum
  ent_coef: 0.1558150008182111
  gamma: 0.9947537003619308
  gae_lambda: 0.6940401326767468
  initial_action_bias: 0.20303168675876349  # Initial action bias as fraction of action space (0.0-1.0)
  net_arch:
    pi: [256, 256]     # Actor
    vf: [256, 256]    # Critic