includes:
  - ../global.yaml

setup:
  action_mode: ds_none  # ds_none, ds_base, ds_none_coeff, ds_base_coeff
  output_size: 1  # (MUST MATCH ABOVE, 1 for none and base, 5 for the _coeff)

  epochs: 3000 # max number of training iterations

  batch_size: 5
  learning_rate: 0.004974414741194879
  initial_action_bias: 0.5160497835425987 # Initial bias as ratio of max_replenish (0.0-1.0)
  neurons_per_hidden_layer: [128, 128]
  inner_layer_activation: elu
  output_layer_activation: relu
  patience: 30  # Number of epochs to wait for improvement before early stopping
  scheduler_factor: 0.6724566870599197 # Factor by which learning rate is reduced when loss plateaus
